// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectMDS.Contexts;

namespace ProiectMDS.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.Chelner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume");

                    b.Property<string>("Prenume");

                    b.Property<int>("Salariu");

                    b.HasKey("Id");

                    b.ToTable("Chelneri");
                });

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NrTelefon");

                    b.Property<string>("Nume");

                    b.Property<string>("Prenume");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChelnerId");

                    b.Property<int>("ClientId");

                    b.Property<int>("Cost");

                    b.Property<int>("MasaId");

                    b.Property<string>("ModPlata");

                    b.HasKey("Id");

                    b.HasIndex("ChelnerId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MasaId");

                    b.ToTable("Comenzi");
                });

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.ComandaMancare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComandaId");

                    b.Property<int>("NrPortii");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("ComenziMancare");
                });

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.Mancare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantitate");

                    b.Property<int?>("ComandaMancareId");

                    b.Property<string>("Nume");

                    b.HasKey("Id");

                    b.HasIndex("ComandaMancareId");

                    b.ToTable("Mancaruri");
                });

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.Masa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Locatie");

                    b.Property<int>("NrLocuri");

                    b.HasKey("Id");

                    b.ToTable("Mese");
                });

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.Comanda", b =>
                {
                    b.HasOne("ProiectMDS.ProiectMDS.Models.Chelner", "Chelner")
                        .WithMany("Comanda")
                        .HasForeignKey("ChelnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProiectMDS.ProiectMDS.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProiectMDS.ProiectMDS.Models.Masa", "Masa")
                        .WithMany()
                        .HasForeignKey("MasaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.ComandaMancare", b =>
                {
                    b.HasOne("ProiectMDS.ProiectMDS.Models.Comanda")
                        .WithMany("ComandaMancare")
                        .HasForeignKey("ComandaId");
                });

            modelBuilder.Entity("ProiectMDS.ProiectMDS.Models.Mancare", b =>
                {
                    b.HasOne("ProiectMDS.ProiectMDS.Models.ComandaMancare")
                        .WithMany("Mancare")
                        .HasForeignKey("ComandaMancareId");
                });
#pragma warning restore 612, 618
        }
    }
}
